GIAM LAG XMAP, THEM AUTO DUNG ITEM :3
pk9r327/Dragonboy pull request #73
Opened 2023-07-04 13:33 UTC by van3177

2023-07-10 01:29 UTC, van3177 commented
lâu thế mấy ngày rồiiiiiiiiiiiiiiiiiiiiii

2023-07-10 06:17 UTC, ElectroHeavenVN requested changes

2023-07-10 06:17 UTC, ElectroHeavenVN commented on AssemblyCSharp/Panel.cs
> +						if (AutoItem.checkList((int)this.currItem.template.id))
Hạn chế sửa hàm của game như thế này, chuyển code sang 1 hàm khác trong class khác rồi gọi hàm đấy trong clas của game

2023-07-14 09:46 UTC, van3177 commented on AssemblyCSharp/Panel.cs
> +						if (AutoItem.checkList((int)this.currItem.template.id))
có đóng góp mới r

2023-07-14 09:47 UTC, van3177 commented on AssemblyCSharp/Panel.cs
> +						if (AutoItem.checkList((int)this.currItem.template.id))
ok

2023-07-14 10:07 UTC, ElectroHeavenVN commented on AssemblyCSharp/Mod/Auto/AutoItem.cs
> +		"By: NVan3177"
vc thế này thì chịu rồi

2023-07-14 10:08 UTC, ElectroHeavenVN commented
Tạm chấp nhận vậy, chẳng qua mình đang phát triển dự án khác thôi

2023-07-14 10:08 UTC, ElectroHeavenVN approved these changes

2023-07-14 10:08 UTC, merged